#define SYS_open          0
#define SYS_close         1
#define SYS_read          2
#define SYS_write         3
#define SYS_lseek         4
#define SYS_fstat         5
#define SYS_isatty        6
#define SYS_getpid        7
#define SYS_kill          8
#define SYS_exit          9
#define SYS_sbrk          10
#define SYS_times         11
#define SYS_wait          12
#define SYS_link          13
#define SYS_unlink        14
#define SYS_stat          15
#define SYS_gettimeofday  16
#define SYS_clock         17